version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 127.0.0.1:5432:5432/tcp
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 127.0.0.1:5050:80
    volumes:
      - pgadmin:/home/rundeck/server/data
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db

  django:
    build: 
      context: ./app
    entrypoint: ['/app/scripts/entrypoint.dev.sh']
    ports:
      - 127.0.0.1:8080:8000
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db:
  pgadmin: